--- 
title: "Linear Algebra"
author: "Deepak Bastola"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Vector Spaces

## Vector Space
A vector space \( V \) over a field \( F \) is a set equipped with two operations:

**Vector Addition:** An operation \( + : V \times V \to V \) that assigns to each pair of vectors \( \alpha, \beta \in V \) a vector \( \alpha + \beta \in V \).

**Scalar Multiplication:** An operation \( \cdot : F \times V \to V \) that assigns to each scalar \( a \in F \) and each vector \( \alpha \in V \) a vector \( a \cdot \alpha \in V \).

These operations must satisfy the following axioms for all vectors \( \alpha, \beta, \gamma \in V \) and all scalars \( a, b \in F \):

1. Vector Addition
   a. Commutativity of Addition: \( \alpha + \beta = \beta + \alpha \)
    b. Associativity of Addition: \( (\alpha + \beta) + \gamma = \alpha + (\beta + \gamma) \)
     c. Identity Element of Addition (Law of Zero): There exists a unique element \( \mathbf{0} \in V \) such that \( \alpha + \mathbf{0} = \alpha \) for all \( \alpha \in V \).
    d. Inverse Elements of Addition: For every \( \alpha \in V \), there exists a unique element \( -\alpha \in V \) such that \( \alpha + (-\alpha) = \mathbf{0} \).
2. Scalar Multiplication
    a. Assosiativity of Scalar Multiplication: \( a \cdot (b \cdot \alpha) = (a b) \cdot \alpha \)
    b. Identity Element of Scalar Multiplication (Law of One): \( 1 \cdot \alpha = \alpha \) for all \( \alpha \in V \), where \( 1 \) is the multiplicative identity in \( F \).
3. Distributivity 
    a. Distributivity of Scalar Multiplication with Respect to Vector Addition: \( a \cdot (\alpha + \beta) = a \cdot \alpha + a \cdot \beta \)
    b. Distributivity of Scalar Multiplication with Respect to Field Addition: \( (a + b) \cdot \alpha = a \cdot \alpha + b \cdot \alpha \)

___________________________________________________________________________________________________________________________
**Examples 1.** The n-tuple space, \( \mathbb{F^n} \). 

In fact, \( \mathbb{F}^n \) is the set of all ordered \( n \)-tuples of elements of \( \mathbb{F} \), i.e.,
    
\[ \mathbb{F}^n = \{(x_1, x_2, \ldots, x_n) \mid x_i \in \mathbb{F} \text{ for all } i = 1, 2, \ldots, n \}. \]
Since if \( \mathbf{u} = (u_1, u_2, \ldots, u_n) \), \( \mathbf{v} = (v_1, v_2, \ldots, v_n) \in \mathbb{F}^n \) and \( a \in \mathbb{F} \), then \[ \mathbf{u} + \mathbf{v} = (u_1 + v_1, u_2 + v_2, \ldots, u_n + v_n) \in \mathbb{F}^n\] because each \( u_i + v_i \in \mathbb{F} \) and    \[ a\mathbf{v} = (a v_1, a v_2, \ldots, a v_n) \in \mathbb{F}^n \] because each \( a v_i \in \mathbb{F} \).

For all vectors \( \mathbf{u}, \mathbf{v}, \mathbf{w} \in \mathbb{F}^n \) and for all scalars $a, b \in \mathbb{F}.$

1. Vector Addition
    a. Commutativity of addition: 
\[ \mathbf{u} + \mathbf{v} = (u_1 + v_1, u_2 + v_2, \ldots, u_n + v_n) = (v_1 + u_1, v_2 + u_2, \ldots, v_n + u_n) = \mathbf{v} + \mathbf{u}\]
    b. Associativity of addition:
\begin{align*}
     (\mathbf{u} + \mathbf{v}) + \mathbf{w} &= (u_1 + v_1, u_2 + v_2, \ldots, u_n + v_n) + \mathbf{w} \\&= ((u_1 + v_1) + w_1, (u_2 + v_2) + w_2, \ldots, (u_n + v_n) + w_n) \\&= (u_1 + (v_1 + w_1), u_2 + (v_2 + w_2), \ldots, u_n + (v_n + w_n))\\&= \mathbf{u} + (v_1 + w_1, v_2 + w_2, \ldots, v_n + w_n) \\&=\mathbf{u} + (\mathbf{v} + \mathbf{w})
\end{align*}
Since addition in \( \mathbb{F} \) is associative, \( (u_i + v_i) + w_i = u_i + (v_i + w_i) \) for all \( i \). 

    c. Identity Element of Addition :
The zero vector \( \mathbf{0} = (0, 0, \ldots, 0) \in \mathbb{F}^n \) acts as the additive identity because 
\[ \mathbf{v} + \mathbf{0} = (v_1 + 0, v_2 + 0, \ldots, v_n + 0) = (v_1, v_2, \ldots, v_n) = \mathbf{v} \]

    d. Inverse Elements of Addition:
For each \( \mathbf{v} = (v_1, v_2, \ldots, v_n) \in \mathbb{F}^n \), there exists \( -\mathbf{v} = (-v_1, -v_2, \ldots, -v_n) \in \mathbb{F}^n\) such that
\[ \mathbf{v} + (-\mathbf{v}) = (v_1 + (-v_1), v_2 + (-v_2), \ldots, v_n + (-v_n)) = (0, 0, \ldots, 0) = \mathbf{0}\]
\end{enumerate}

2. Scalar Multiplication
    a. Associativity of scalar multiplication:
\begin{align*}
     a(b \mathbf{v}) &= a(b v_1, b v_2, \ldots, b v_n) = (a(b v_1), a(b v_2), \ldots, a(b v_n)) \\&= ((ab) v_1, (ab) v_2, \ldots, (ab) v_n) = (ab) \mathbf{v}
\end{align*}
    b. Identity Element of Scalar Multiplication:
\[ 1 \mathbf{v} = 1(v_1, v_2, \ldots, v_n) = (1 v_1, 1 v_2, \ldots, 1 v_n) = (v_1, v_2, \ldots, v_n) = \mathbf{v}\]
3. Distributivity 
    a. Distributivity of scalar multiplication with respect to vector addition
\begin{align*}
 a(\mathbf{u} + \mathbf{v}) &= a(u_1 + v_1, u_2 + v_2, \ldots, u_n + v_n) \\&= (a(u_1 + v_1), a(u_2 + v_2), \ldots, a(u_n + v_n)) \\&= (a u_1 + a v_1, a u_2 + a v_2, \ldots, a u_n + a v_n) \\&= a \mathbf{u} + a \mathbf{v}   
\end{align*}

    b. Distributivity of scalar multiplication with respect to field addition
\begin{align*}
     (a + b)\mathbf{v} &= (a + b)(v_1, v_2, \ldots, v_n) = ((a + b)v_1, (a + b)v_2, \ldots, (a + b)v_n) \\&= (a v_1 + b v_1, a v_2 + b v_2, \ldots, a v_n + b v_n) \\&= a \mathbf{v} + b \mathbf{v}
     \end{align*}

Thus, \( \mathbb{F}^n \) satisfies all these axioms, it is a vector space.